### ISSUE TITLE
Append Scale

### ISSUE THREAD

**Issue by Verticalsrl** [Verticalsrl/plugin_FTTH#2]
Non capisco la logica se confronta i dati da shp con il db e se mancano campi me li chiede oppure ha un suo tracciato standard da rispettare, adesso mi chiede campi tipo
ebw_propri	
ebw_stato_	
ebw_note	

questi campi non servono a niente la tabella scale deve essere la solita da sempre

**Comment by armagaet** [comment]
Su alcuni layer scala questi campi erano popolati.
ho deciso di inserirli nella funzione s_alter_scala_fn, in modo tale che quando si importano le nuove scale (da zero o da appendere) lui crea questi campi e si porta dietro queste informazioni.
Certo, sui "vecchi" DB la tabella SCALA probabilmente non ha questi campi, bisogna aggiungerli.
In altri casi ripeto mi son ritrovato con questi campi popolati e mi sembrava corretto portarsi dietro queste informazioni, onde evitare soprattutto di doverlo fare in futuro.
In questi casi, per creare i campi che servono, NON SI PUO' rilanciare manualmente la funzione s_alter_scala_fn, poichè questa funzione, oltre a creare/rinominare i campi che servono, aggiorna anche il campo n_ui_originali ponendolo uguale alle n_ui, quindi se il progetto è già avanti si rischia di RESETTARE tutto il lavoro.
Finchè il tracciato non si stabilizza bisogna aggiungere i nuovi campi a mano.

**Comment by armagaet** [comment]
Ho modificato la funzione "s_alter_scala_fn" cosicchè la si può lanciare (manualmente) per creare sul layer scala tutti quei campi che non dovessero esserci nel caso di layer creato con vecchie versioni del plugin.
questo perchè ho posto la condizione:

_UPDATE %s.%s SET n_ui_originali = n_ui WHERE n_ui_originali IS NULL;_
