### ISSUE TITLE
Campi WolkOut

### ISSUE THREAD

**Issue by Verticalsrl** [Verticalsrl/plugin_FTTH#4]
Vanno tolti i campi del wolkout che avevamo messo a settembre perchè hanno cambiato la logica, togliamoli (commentali) solo su:
**Layer Cavo**
wo	varchar	6	0	-1	0	0	0	0		0			default		0	0
tubi	int2	16	0	-1	0	0	0	0		0					0	0
tubo1diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo1liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo2diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo2liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo3diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo3liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo4diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo4liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo5diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo5liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo6diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo6liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo7diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo7liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo8diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo8liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo9diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo9liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo10diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo10liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo11diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo11liber	int2	16	0	-1	0	0	0	0		0					0	0
tubo12diam	int2	16	0	-1	0	0	0	0		0					0	0
tubo12liber	int2	16	0	-1	0	0	0	0		0					0	0

**Pozzetto**
wo	varchar	6	0	-1	0	0	0	0		0			default		0	0
stato	varchar	50	0	-1	0	0	0	0		0			default		0	0
chiuso	varchar	30	0	-1	0	0	0	0		0			default		0	0
marchio	varchar	30	0	-1	0	0	0	0		0			default		0	0
lato_1	varchar	10	0	-1	0	0	0	0		0			default		0	0
lato_2	varchar	10	0	-1	0	0	0	0		0			default		0	0
lato_3	varchar	10	0	-1	0	0	0	0		0			default		0	0
lato_4	varchar	10	0	-1	0	0	0	0		0			default		0	0
foto_l1	varchar	250	0	-1	0	0	0	0		0			default		0	0
progetto	varchar	25	0	-1	0	0	0	0		0			default		0	0
proprieta	varchar	25	0	-1	0	0	0	0		0			default		0	0
cassetta_ed	varchar	2	0	-1	0	0	0	0		0			default		0	0
foto_l2	varchar	250	0	-1	0	0	0	0		0			default		0	0
foto_l3	varchar	250	0	-1	0	0	0	0		0			default		0	0
foto_l4	varchar	250	0	-1	0	0	0	0		0			default		0	0

**Comment by armagaet** [comment]
Modificato file creazione_funzione_saltertable.sql: le modifiche richieste sono state eseguite e committate.
